os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.10.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
before_script:
  - cp src/test/resources/config/keystore.jks src/main/resources/config/keystore.jks # we need the keystore to run our app, and we need our app to run e2e tests
  - ./gradlew bootRun 1> /dev/null &
  - sleep 60 # give spring boot some time to start
script:
  - ./gradlew test
  - yarn test
  - yarn e2e
  - ./gradlew bootRepackage -Pprod buildDocker -x test
  - killall java # stop running MP instance
  - docker-compose -f src/main/docker/app.yml up -d # spin up production mode application
  - sed -i 's|http://localhost:8080/|http://localhost:8080/managementportal/|' src/test/javascript/protractor.conf.js  # modify protractor config to production environment
  - grep baseUrl src/test/javascript/protractor.conf.js
  - sleep 120 # wait for app to start up
  - docker-compose -f src/main/docker/app.yml logs
  - yarn e2e # run e2e tests against production mode
  - docker-compose -f src/main/docker/app.yml down -v # clean up containers and volumes
  - git checkout src/test/javascript/protractor.conf.js  # revert protractor configuration
  # on release branches, also test if the Dockerfile for automated builds on dockerhub still builds
  - if [[ $TRAVIS_BRANCH == add-production-* ]]; then docker build -t managementportal .; fi
after_script:
  - ./gradlew sendCoverageToCodacy
deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file: "build/libs/*.war"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew oauth-client-util:bintrayUpload
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew radar-auth:bintrayUpload
    skip_cleanup: true
    on:
      tags: true
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change]
