# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
zuul:
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500
    retryable: true
    routes:
        ManagementPortal:
            path: /oauthserver/oauth/**
            url: http://localhost:8080/oauth
ribbon:
    eureka:
        enabled: false

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

management:
    security:
        roles: ROLE_SYS_ADMIN
        enabled: false # disabling security check for health to allow kubernetes to detect the health of the service
    context-path: /management
    health:
        diskspace:
            enabled: false # disabling diskspace as the standard config, since we have removed security check for health endpoint
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
        db:
            enabled: true
spring:
    application:
        name: ManagementPortal
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.radarcns.management.hibernate.CaseSensitivePhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            org.hibernate.envers:
                store_data_at_delete: true
                audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
                audit_strategy_validity_store_revend_timestamp: true
                global_with_modified_flag: true
                track_entities_changed_in_revision: true
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3

server:
    session:
        cookie:
            http-only: true

info:
    project:
        version: #project.version#

# ===================================================================
# ManagementPortal specific properties
#
# ===================================================================
managementportal:
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: ManagementPortal@localhost
    oauth:
        keyStorePassword: radarbase
        signingKeyAlias: radarbase-managementportal-ec
        enablePublicKeyVerifiers: false

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    cors:
        allowed-origins: '*'
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: Authorization, Content-Type
        #exposed-headers:
        allow-credentials: true
        max-age: 1800
    swagger:
        default-include-pattern: /api/.*
        title: ManagementPortal API
        description: ManagementPortal API documentation
        version: #project.version#
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license: Apache 2.0
        license-url: https://github.com/RADAR-base/ManagementPortal/blob/master/LICENSE.md
    ribbon:
        display-on-active-profiles: dev

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:
