version: '2'
services:
    managementportal-app:
        image: managementportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://managementportal-postgresql:5432/managementportal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - JAVA_OPTS="-Xmx256m"  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
        ports:
            - 8080:8080
    managementportal-postgresql:
        extends:
            file: postgresql.yml
            service: managementportal-postgresql
