version: '2'
services:
    managementportal-postgresql:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=radarbase
            - POSTGRES_PASSWORD=radarbase
            - POSTGRES_DB=managementportal
