version: '2'
services:
    managementportal-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=radarbase
            - POSTGRES_PASSWORD=radarbase
            - POSTGRES_DB=managementportal
