name: Snyk scheduled test

on:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          json: true
          args: --all-projects --configuration-matching=runtimeClasspath --configuration-matching=compileClasspath --policy-path=.snyk
        if: ${{ !cancelled() }}

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        with:
          report-file: snyk.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() }}
