name: Snyk scheduled test

on:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Install Snyk
        run: npm install snyk@latest -g

      - name: Log in to snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth

      - name: Run Snyk to check for vulnerabilities
        run: >-
          snyk test
          --all-projects
          --configuration-matching=runtimeClasspath
          --configuration-matching=compileClasspath
          --policy-path=.snyk
          --json-file-output=snyk.json

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        with:
          report-file: snyk.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() }}
