name: Snyk test

on:
 - pull_request

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --all-projects --configuration-matching=runtimeClasspath --configuration-matching=compileClasspath --policy-path=.snyk
