name: Snyk test

on:
 - pull_request

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: gradle

      - name: Install Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install snyk@latest -g
          snyk auth

      - name: Run Snyk to check for vulnerabilities
        run: >
          snyk test
          --severity-threshold=high
          --all-projects
          --configuration-matching=runtimeClasspath
          --configuration-matching=compileClasspath
          --policy-path=.snyk
